site_name: "bitr-db"
site_description: "Documentación del proyecto bitr-db"
site_author: "Aldo Villagra"
site_url: https://.github.io/bitr-db/
repo_url: "https://github.com//bitr-db"

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - content.code.copy
    - toc.integrate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            docstring_options:
              ignore_init_summary: true
            show_source: true
            show_signature: true
            separate_signature: true
            members_order: alphabetical

nav:
  - Inicio: index.md
  - Código:
      - "bitr_db": "reference/bitr_db.md"
  - Pruebas: tests.md
